# Site name
site_name: Module 5 - Data Engineering Product Development
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - Agenda:
    - Day 1: agenda/day1.md
    - Day 2: agenda/day2.md
    - Day 3: agenda/day3.md

  - "Day 1 - Foundation & Setup":
    - "The Scenario": day1/scenario.md
    - "Your Mission": day1/your-mission.md
    - "Review the sample data files": day1/sample-data.md
    - "Design your pipeline architecture": day1/design-pipeline.md
    - "Create a GitHub repository": day1/create-repo.md
    - "Introduce GitHub Projects": day1/create-project.md
    - "Set up Kanban board": day1/project-tasks.md
    - "Write first Python code": day1/write-code.md

  - "Day 2 - Build & Test Pyhon Package":
    - "VM Setup & Welcome": day2/vm-setup.md
    - "Explain function - Data Ingestion": day2/ingestion.md
    - "Write function - Data Ingestion": day2/ingestion-enhancements.md
    - "Explain function - Data Cleaning": day2/cleaning.md
    - "Write function - Data Cleaning": day2/cleaning-enhancements.md
    - "Python Testing": day2/python-testing.md
    - "Write unit tests": day2/cleaning-tests.md
    - "Python Test Coverage": day2/coverage.md
    - "Achive test coverage": day2/coverage-goal.md

  - "Day 3 - Automation & Integration":
    - "GitHub Actions": day3/github-actions.md
    - "GitHub Actions ~ Trigger Workflow": day3/github-workflow.md
    - "Pull Request Workflow": day3/gh-branch.md
    - "Complete Your Own PR Workflow": day3/pull-request.md

  - Resources: resources.md

not_in_nav: |
  404.md
  trainer.md
  day1/create-diagram.md
  day1/github-template.md
  day3/observation.md


# Theme
theme:
    features:
      - toc.integrate
      - content.code.copy
    name: material
    icon:
      logo: material/database

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
  - glightbox


